{% set name = "aiohappyeyeballs" %}
{% set version = "2.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiohappyeyeballs-{{ version }}.tar.gz
  sha256: 9b05052f9042985d32ecbe4b59a77ae19c006a78f1344d7fdad69d28ded3d0b0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - aiohappyeyeballs
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/aio-libs/aiohappyeyeballs
  summary: Happy Eyeballs for asyncio
  license: PSF-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
